### ISSUE TITLE
widget does not work on AWS sagemaker

### ISSUE THREAD

**Issue by loctruong96** [gereleth/jupyter-bbox-widget#11]
![image](https://user-images.githubusercontent.com/8007433/194968532-532659dd-ae44-42b3-ac54-ac82bd31ad9e.png)

[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'BBoxModel' from module 'jupyter-bbox-widget'
Error: Script error for "jupyter-bbox-widget"
http://requirejs.org/docs/errors.html#scripterror

I've added the jupyter --version here for inspection as well.

Selected Jupyter core packages...
IPython          : 7.33.0
ipykernel        : 5.5.6
ipywidgets       : 8.0.2
jupyter_client   : 6.1.12
jupyter_core     : 4.11.1
jupyter_server   : not installed
jupyterlab       : 1.2.21
nbclient         : not installed
nbconvert        : 5.6.1
nbformat         : 5.6.1
notebook         : 5.7.15
qtconsole        : 5.3.2
traitlets        : 5.4.0

more logs

Running setup.py develop for jupyter-bbox-widget
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [43 lines of output]
        running develop
        running jsdeps
        /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py:774: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
          % (opt, underscore_opt)
        /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
          warnings.warn(msg, warning_class)
        /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          EasyInstallDeprecationWarning,
        /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          setuptools.SetuptoolsDeprecationWarning,
        `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
        Traceback (most recent call last):
          File "<string>", line 36, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/ec2-user/jupyter-bbox-widget/setup.py", line 101, in <module>
            setup(**setup_args)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
            return distutils.core.setup(**attrs)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
            self.run_command(cmd)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
            cmd_obj.run()
          File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 474, in run
            [self.run_command(cmd) for cmd in cmds]
          File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 474, in <listcomp>
            [self.run_command(cmd) for cmd in cmds]
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
            self.distribution.run_command(command)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
            super().run_command(command)
          File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
            cmd_obj.run()
          File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 270, in run
            c.run()
          File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 395, in run
            raise ValueError(('missing files: %s' % missing))
        ValueError: missing files: ['/home/ec2-user/jupyter-bbox-widget/jupyter_bbox_widget/nbextension/static/index.js', '/home/ec2-user/jupyter-bbox-widget/lib/plugin.js']
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of jupyter-bbox-widget
  Moving to /home/ec2-user/SageMaker/.persisted_conda/label_env/etc/jupyter/nbconfig/notebook.d/jupyter_bbox_widget.json
   from /tmp/pip-uninstall-gkitszff/jupyter_bbox_widget.json
  Moving to /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/jupyter_bbox_widget-0.5.0.dist-info/
   from /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/~upyter_bbox_widget-0.5.0.dist-info
  Moving to /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/jupyter_bbox_widget/
   from /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/~upyter_bbox_widget
  Moving to /home/ec2-user/SageMaker/.persisted_conda/label_env/share/jupyter/lab/extensions/
   from /home/ec2-user/SageMaker/.persisted_conda/label_env/share/jupyter/lab/~xtensions
  Moving to /home/ec2-user/SageMaker/.persisted_conda/label_env/share/jupyter/nbextensions/jupyter_bbox_widget/
   from /home/ec2-user/SageMaker/.persisted_conda/label_env/share/jupyter/nbextensions/~upyter_bbox_widget
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [43 lines of output]
    running develop
    running jsdeps
    /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py:774: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      % (opt, underscore_opt)
    /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
      warnings.warn(msg, warning_class)
    /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/command/easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    /home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/ec2-user/jupyter-bbox-widget/setup.py", line 101, in <module>
        setup(**setup_args)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
        self.run_command(cmd)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 474, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 474, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
        super().run_command(command)
      File "/home/ec2-user/SageMaker/.persisted_conda/label_env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.run()
      File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 270, in run
        c.run()
      File "/home/ec2-user/jupyter-bbox-widget/setupbase.py", line 395, in run
        raise ValueError(('missing files: %s' % missing))
    ValueError: missing files: ['/home/ec2-user/jupyter-bbox-widget/jupyter_bbox_widget/nbextension/static/index.js', '/home/ec2-user/jupyter-bbox-widget/lib/plugin.js']
    [end of output]

**Comment by gereleth** [comment]
I must say I've never used Sagemaker. =)

Jupyterlab version 1 seems rather old, maybe the current version 3 would work better.

Development install command complains about `npm` being unavailable - maybe try installing npm first?

**Comment by loctruong96** [comment]
yeah I abandoned sagemaker and setup my own jupyter instance and it works great. thanks!
